# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calculator(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(331, 542)
        calculator.setMinimumSize(QtCore.QSize(331, 542))
        calculator.setMaximumSize(QtCore.QSize(331, 542))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        calculator.setFont(font)
        calculator.setStyleSheet("* {\n"
"font-family:Century Gothic;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#ddd;\n"
"border:#aaa;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#aaa;\n"
"border:#aaa;\n"
"\n"
"}\n"
"\n"
"QTextBrowser{\n"
"font-size:24px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 311, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(10, 200, 71, 71))
        self.seven.setObjectName("seven")
        self.seven.clicked.connect(self.get_seven)
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(90, 200, 71, 71))
        self.eight.setObjectName("eight")
        self.eight.clicked.connect(self.get_eight)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 200, 71, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.get_nine)
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(250, 200, 71, 71))
        self.plus.setObjectName("plus")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(10, 360, 71, 71))
        self.one.setObjectName("one")
        self.one.clicked.connect(self.get_one)
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(170, 360, 71, 71))
        self.three.setObjectName("three")
        self.three.clicked.connect(self.get_three)
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(90, 360, 71, 71))
        self.two.setObjectName("two")
        self.two.clicked.connect(self.get_two)
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(90, 280, 71, 71))
        self.five.setObjectName("five")
        self.five.clicked.connect(self.get_five)
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(250, 280, 71, 231))
        self.equal.setObjectName("equal")
    
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(10, 280, 71, 71))
        self.four.setObjectName("four")
        self.four.clicked.connect(self.get_four)
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(170, 280, 71, 71))
        self.six.setObjectName("six")
        self.six.clicked.connect(self.get_six)
        self.ziro = QtWidgets.QPushButton(self.centralwidget)
        self.ziro.setGeometry(QtCore.QRect(10, 440, 151, 71))
        self.ziro.setObjectName("ziro")
        self.ziro.clicked.connect(self.get_ziro)
        self.Decimal = QtWidgets.QPushButton(self.centralwidget)
        self.Decimal.setGeometry(QtCore.QRect(170, 440, 71, 71))
        self.Decimal.setObjectName("Decimal")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(170, 120, 71, 71))
        self.multiply.setObjectName("multiply")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 120, 71, 71))
        self.pushButton.setObjectName("pushButton")
        self.Division = QtWidgets.QPushButton(self.centralwidget)
        self.Division.setGeometry(QtCore.QRect(90, 120, 71, 71))
        self.Division.setObjectName("Division")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(250, 120, 71, 71))
        self.minus.setObjectName("minus")
        calculator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(calculator)
        self.statusbar.setObjectName("statusbar")
        calculator.setStatusBar(self.statusbar)

        self.retranslateUi(calculator)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    entry_num = ''

    first_entry_num = ''
    second_entry_num = ''

    def get_ziro(self):
        self.entry_num += '0'
        print(self.entry_num)
        return self.entry_num

    def get_one(self):
        self.entry_num += '1'
        print(self.entry_num)
        return self.entry_num

    def get_two(self):
        self.entry_num += '2'
        print(self.entry_num)
        return self.entry_num

    def get_three(self):
        self.entry_num += '3'
        print(self.entry_num)
        return self.entry_num

    def get_four(self):
        self.entry_num += '4'
        print(self.entry_num)
        return self.entry_num

    def get_five(self):
        self.entry_num += '5'
        print(self.entry_num)
        return self.entry_num

    def get_six(self):
        self.entry_num += '6'
        print(self.entry_num)
        return self.entry_num

    def get_seven(self):
        self.entry_num += '7'
        print(self.entry_num)
        return self.entry_num

    def get_eight(self):
        self.entry_num += '8'
        print(self.entry_num)
        return self.entry_num

    def get_nine(self):
        self.entry_num += '9'
        print(self.entry_num)
        return self.entry_num





    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "PhiloLearn Calculator"))
        self.textBrowser.setPlaceholderText(_translate("calculator", "philolearn"))
        self.seven.setText(_translate("calculator", "7"))
        self.eight.setText(_translate("calculator", "8"))
        self.pushButton_3.setText(_translate("calculator", "9"))
        self.plus.setText(_translate("calculator", "+"))
        self.one.setText(_translate("calculator", "1"))
        self.three.setText(_translate("calculator", "3"))
        self.two.setText(_translate("calculator", "2"))
        self.five.setText(_translate("calculator", "5"))
        self.equal.setText(_translate("calculator", "="))
        self.four.setText(_translate("calculator", "4"))
        self.six.setText(_translate("calculator", "6"))
        self.ziro.setText(_translate("calculator", "0"))
        self.Decimal.setText(_translate("calculator", "."))
        self.multiply.setText(_translate("calculator", "X"))
        self.pushButton.setText(_translate("calculator", "C"))
        self.Division.setText(_translate("calculator", "/"))
        self.minus.setText(_translate("calculator", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calculator = QtWidgets.QMainWindow()
    ui = Ui_calculator()
    ui.setupUi(calculator)
    calculator.show()
    sys.exit(app.exec_())
